### ISSUE TITLE
Man page is a bit unclear about set-dns and pppd-dns

### ISSUE THREAD

**Issue by yennor** [adrienverge/openfortivpn#429]
In the man page there is a config option "set-dns", which when you set that to 0
is supposed to "Set if openfortivpn should add VPN nameservers in /etc/resolv.conf when tunnel is up. ". That doesn't seem to work. Then you look around the man page a bit more, and you find a second setting:
--pppd-no-peerdns which is supposed to do the same but that time that pppd doesn't rewrite resolv.conf. I guess for most users the difference won't be obvious. Usually you'd expect the set-dns = 0 setting to work. So it should be mentioned in those settings, that a second one exist, and if one doesn't work one should try out the other one.
Additionally. You can't use --pppd-no-peerdns in a config file. There you have to use
pppd-use-peerdns = 0.
But that setting is not documented in the man page.

**Comment by DimitriPapadopoulos** [comment]
See #330. I had tried to fix this but had gone to far which resulted in serious bugs. This time we just need to document or slightly rename options - with compatibility in mind.

**Comment by mrbaseman** [comment]
which version are we talking about? In reaction to the regression that resulted from #330 I have updated the man page in https://github.com/adrienverge/openfortivpn/commit/07d9623ef123e99e0dfdbef9299c7e4ebffffd2b. Some aspects that you mention are covered, so perhaps this is already solved in the current master branch, but I'm open to further suggestions to improve the man page.

**Comment by yennor** [comment]
The version of the last release.

The man page already looks better now, but it still doesn't mention the existence of
pppd-use-peerdns = x
only --pppd-no-peerdns which you can't use inside of a config file.

**Comment by mrbaseman** [comment]
Well, it is mentioned in the [example config file](https://github.com/adrienverge/openfortivpn/blob/master/doc/openfortivpn.1.in#L254).
But you are right, there is a slight inconsistency between command line options and what is accepted in the config file.
I have opened #432 to address that.

**Comment by mrbaseman** [comment]
I have just merged this into our master branch. Together with the above mentioned update to the man page this will be included in the next release.

**Comment by mrbaseman** [comment]
The man page has been updated with the [1.9.0](https://github.com/adrienverge/openfortivpn/releases/tag/v1.9.0) release, which also contains the change that makes the accepted config file options and command line options more consistent.
